#!/usr/bin/env python3
import webbrowser as wb
from eightd_audioconv.server import run
# import eightd_audioconv.server as server
# from . import run

if __name__ == '__main__':
    run()
    wb.open_new_tab('http://localhost:5000/')
